name: FrostBoats
version: '${project.version}'
main: com.articreep.frostboats.FrostBoats
api-version: '1.20'
authors: [ Arti_Creep ]
description: Boats, but with Frost Walker, so you can boat over lakes of ice instead of water.
commands:
  reloadfrostboats:
    description: Reloads recipes and config values.
    usage: /reloadfrostboats
    permission: frostboats.reload
